### PR TITLE
fix(tsconfig): typo in tsconfig

### PR DESCRIPTION
**Pull request by zaidchauhan**
It's embarrassing, but yes I made typo error and this pr will fix it.

### CODE REVIEW

**Comment by zaidchauhan** [comment]
@jedmao Sorry 🙏 
I made typo but when I run the build command locally (even now) it's generating proper output even with typo. However, the same is not true for npm publish.

Request you to approve this 🙏

**Review by jednano — APPROVED** [review]

**Comment by zaidchauhan** [comment]
@jedmao  Still it's not generating util.js in npm source, can you please take a look ? as package is broken in absence of required imports

**Comment by zaidchauhan** [comment]
@jedmao https://github.com/jedmao/redux-mock-store/pull/61
Never published npm package before, I was not aware that it requires to add entry in to files property in package.json

**Pull request merged**
