### PR TITLE
Replace lodash function with native

### PR DESCRIPTION
**Pull request by zaidchauhan**
To avoid issue with ESM bundle, replaced lodash function with native code (Browser support IE9 and above)

Also changed file structure to move all test files from src to test directory.

### CODE REVIEW

**Review by jednano — APPROVED** [review]
Great work!

**Comment by jednano** [comment]
All I need you to do is `git reset —soft head~1 && git add . && npm run commit` so that when I merge it will automatically bump the version. Thanks!

**Comment by zaidchauhan** [comment]
@jedmao Done :)

**Comment by zaidchauhan** [comment]
@jedmao If you are ok, I request you to open Issue feature from setting for this repo.

**Comment by jednano** [comment]
Didn’t realize it wasn’t enabled. I’ll do it now.

**Comment by zaidchauhan** [comment]
@jedmao Sorry, in last PR there is build issue.
I raised new PR for fixes - https://github.com/jedmao/redux-mock-store/pull/52

**Comment by zaidchauhan** [comment]
package seems to be broken due to that, request you to merge as soon as possible 🙏

**Pull request merged**
